import type { Prospect } from "@/app/dashboard/prospeccion/page";
import type { Deal } from "@/app/dashboard/seguimiento/page";

// ── Datos ficticios para desarrollo local ─────────────────────────────────────
// Actívados con NEXT_PUBLIC_USE_MOCK=true en .env.local
// NUNCA se usan en producción (la variable no existe en Vercel)

export type SuggestedProspect = {
  id: string;
  name: string;
  country: string;
  category: string;
  razon: string;         // por qué la IA los sugiere
  contactoCargo: string; // cargo estimado del comprador de categoría
  canal: "WhatsApp" | "Email";
  semana: string;        // "2026-W24"
  idioma: "es" | "en";
};

// Semana 9–15 junio 2026 (W24)
export const MOCK_SUGGESTED_PROSPECTS: SuggestedProspect[] = [
  {
    id: "sug-001",
    name: "Hipermás El Salvador",
    country: "El Salvador",
    category: "Snacks & Confitería",
    razon: "Cadena de 18 hipermercados. Sin distribuidor activo en categoría Snacks según perfil LinkedIn de su equipo de compras.",
    contactoCargo: "Jefe de Compras",
    canal: "WhatsApp",
    semana: "2026-W24",
    idioma: "es",
  },
  {
    id: "sug-002",
    name: "Distribuidora Castillo & Asociados",
    country: "Honduras",
    category: "Bebidas & Snacks",
    razon: "Distribuidora regional con cobertura en 6 departamentos. Busca ampliar portafolio de snacks para el canal tradicional.",
    contactoCargo: "Gerente Comercial",
    canal: "WhatsApp",
    semana: "2026-W24",
    idioma: "es",
  },
  {
    id: "sug-003",
    name: "Selectos Supermercados",
    country: "El Salvador",
    category: "Confitería",
    razon: "Cadena nacional con 25 puntos de venta. Su exhibidor de confitería lleva más de 6 meses sin renovar proveedor.",
    contactoCargo: "Category Manager",
    canal: "Email",
    semana: "2026-W24",
    idioma: "es",
  },
  {
    id: "sug-004",
    name: "Super Selectos Nicaragua",
    country: "Nicaragua",
    category: "Limpieza del Hogar",
    razon: "Segunda cadena de supermercados del país. Perfil de compras activo en LinkedIn con búsquedas recientes de proveedores de limpieza.",
    contactoCargo: "Jefe de Compras",
    canal: "WhatsApp",
    semana: "2026-W24",
    idioma: "es",
  },
  {
    id: "sug-005",
    name: "IGA Supermarkets Jamaica",
    country: "Jamaica",
    category: "Bebidas & Confitería",
    razon: "Franquicia IGA con 9 tiendas en Kingston y Montego Bay. Compradores activos en ferias regionales del Caribe.",
    contactoCargo: "Purchasing Manager",
    canal: "Email",
    semana: "2026-W24",
    idioma: "en",
  },
  {
    id: "sug-006",
    name: "Mega Depot Trinidad",
    country: "Trinidad",
    category: "Snacks & Limpieza del Hogar",
    razon: "Cash & Carry mayorista con 3 sucursales. Importa directamente de Panamá y Colombia. Contacto identificado en directorio TTMA.",
    contactoCargo: "Procurement Manager",
    canal: "Email",
    semana: "2026-W24",
    idioma: "en",
  },
  {
    id: "sug-007",
    name: "La Torre Guatemala",
    country: "Guatemala",
    category: "Cuidado Personal",
    razon: "Cadena de tiendas de descuento con presencia en 12 ciudades. Alta rotación en categoría cuidado personal según reporte sectorial.",
    contactoCargo: "Gerente de Compras",
    canal: "WhatsApp",
    semana: "2026-W24",
    idioma: "es",
  },
  {
    id: "sug-008",
    name: "Courts Barbados",
    country: "Barbados",
    category: "Confitería & Snacks",
    razon: "Retail establecido en Bridgetown con sección de alimentos en expansión. Busca proveedores latinoamericanos según su newsletter comercial.",
    contactoCargo: "Buying Manager",
    canal: "Email",
    semana: "2026-W24",
    idioma: "en",
  },
  {
    id: "sug-009",
    name: "Corporación Multi Inversiones CR",
    country: "Costa Rica",
    category: "Snacks & Bebidas",
    razon: "Grupo empresarial con cadena Pollo Campero y puntos retail. Licitación abierta para snacks en canales de conveniencia.",
    contactoCargo: "Category Manager",
    canal: "WhatsApp",
    semana: "2026-W24",
    idioma: "es",
  },
  {
    id: "sug-010",
    name: "United Grocers Barbados",
    country: "Barbados",
    category: "Bebidas & Limpieza del Hogar",
    razon: "Mayorista caribeño con red de 40 clientes minoristas en Barbados y Santa Lucía. Asistente a feria CHTA 2026.",
    contactoCargo: "Sales & Purchasing Director",
    canal: "Email",
    semana: "2026-W24",
    idioma: "en",
  },
];

export const MOCK_PROSPECTS: Prospect[] = [
  {
    id: "mock-001",
    name: "Supermercados La Colonia",
    country: "Guatemala",
    status: "sin acción",
    seller: "Carlos Méndez",
    vendorIds: [],
    category: "Snacks & Confitería",
    lastContact: "2026-05-20",
    nextContact: "2026-06-10",
    updatedAt: "3sem",
    createdAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "mock-002",
    name: "Distribuidora Rojas & Hijos",
    country: "Costa Rica",
    status: "contacto efectivo",
    seller: "Jenni Benarroch",
    vendorIds: [],
    category: "Confitería",
    lastContact: "2026-06-08",
    nextContact: "2026-06-12",
    updatedAt: "ayer",
    createdAt: "2026-05-10T00:00:00.000Z",
  },
  {
    id: "mock-003",
    name: "Mercado Central CR",
    country: "Costa Rica",
    status: "propuesta enviada",
    seller: "María López",
    vendorIds: [],
    category: "Bebidas & Snacks",
    lastContact: "2026-06-05",
    nextContact: "2026-06-11",
    updatedAt: "4d",
    createdAt: "2026-05-12T00:00:00.000Z",
  },
  {
    id: "mock-004",
    name: "Super 99 Panama",
    country: "Panamá",
    status: "negociación",
    seller: "Jenni Benarroch",
    vendorIds: [],
    category: "Cuidado Personal",
    lastContact: "2026-06-07",
    nextContact: "2026-06-14",
    updatedAt: "2d",
    createdAt: "2026-04-20T00:00:00.000Z",
  },
  {
    id: "mock-005",
    name: "Do it Center Jamaica",
    country: "Jamaica",
    status: "sin acción",
    seller: "Carlos Méndez",
    vendorIds: [],
    category: "Limpieza del Hogar",
    lastContact: "2026-05-15",
    nextContact: "2026-06-09",
    updatedAt: "3sem",
    createdAt: "2026-05-05T00:00:00.000Z",
  },
  {
    id: "mock-006",
    name: "Massy Stores Trinidad",
    country: "Trinidad",
    status: "contacto efectivo",
    seller: "María López",
    vendorIds: [],
    category: "Confitería & Bebidas",
    lastContact: "2026-06-09",
    nextContact: "2026-06-13",
    updatedAt: "hoy",
    createdAt: "2026-05-18T00:00:00.000Z",
  },
  {
    id: "mock-007",
    name: "Walmart Guatemala Ciudad",
    country: "Guatemala",
    status: "inactivo",
    seller: "Carlos Méndez",
    vendorIds: [],
    category: "Snacks",
    lastContact: "2026-04-10",
    nextContact: "",
    updatedAt: "2mes",
    createdAt: "2026-03-15T00:00:00.000Z",
  },
  {
    id: "mock-008",
    name: "PriceSmart Costa Rica",
    country: "Costa Rica",
    status: "sin acción",
    seller: "Jenni Benarroch",
    vendorIds: [],
    category: "Snacks & Bebidas",
    lastContact: "2026-06-02",
    nextContact: "2026-06-10",
    updatedAt: "1sem",
    createdAt: "2026-05-22T00:00:00.000Z",
  },
  {
    id: "mock-009",
    name: "Palí Honduras",
    country: "Honduras",
    status: "propuesta enviada",
    seller: "María López",
    vendorIds: [],
    category: "Confitería",
    lastContact: "2026-06-06",
    nextContact: "2026-06-13",
    updatedAt: "3d",
    createdAt: "2026-05-25T00:00:00.000Z",
  },
  {
    id: "mock-010",
    name: "Massy Supermarket Barbados",
    country: "Barbados",
    status: "sin acción",
    seller: "Carlos Méndez",
    vendorIds: [],
    category: "Cuidado Personal & Hogar",
    lastContact: "2026-05-28",
    nextContact: "2026-06-11",
    updatedAt: "1sem",
    createdAt: "2026-05-20T00:00:00.000Z",
  },
  {
    id: "mock-011",
    name: "Maxibodega El Salvador",
    country: "El Salvador",
    status: "negociación",
    seller: "Jenni Benarroch",
    vendorIds: [],
    category: "Snacks & Confitería",
    lastContact: "2026-06-08",
    nextContact: "2026-06-16",
    updatedAt: "ayer",
    createdAt: "2026-04-30T00:00:00.000Z",
  },
  {
    id: "mock-012",
    name: "Super BM Guatemala",
    country: "Guatemala",
    status: "contacto efectivo",
    seller: "María López",
    vendorIds: [],
    category: "Bebidas",
    lastContact: "2026-06-09",
    nextContact: "2026-06-15",
    updatedAt: "hoy",
    createdAt: "2026-05-28T00:00:00.000Z",
  },
  {
    id: "mock-013",
    name: "Hi-Lo Food Stores Jamaica",
    country: "Jamaica",
    status: "propuesta enviada",
    seller: "María López",
    vendorIds: [],
    category: "Confitería",
    lastContact: "2026-06-04",
    nextContact: "2026-06-12",
    updatedAt: "5d",
    createdAt: "2026-05-15T00:00:00.000Z",
  },
  {
    id: "mock-014",
    name: "Automercado CR",
    country: "Costa Rica",
    status: "cliente",
    seller: "Jenni Benarroch",
    vendorIds: [],
    category: "Snacks & Cuidado Personal",
    lastContact: "2026-06-07",
    nextContact: "2026-06-21",
    updatedAt: "2d",
    createdAt: "2026-02-10T00:00:00.000Z",
  },
  {
    id: "mock-015",
    name: "Giant Supermarket Jamaica",
    country: "Jamaica",
    status: "sin acción",
    seller: "Carlos Méndez",
    vendorIds: [],
    category: "Bebidas & Snacks",
    lastContact: "2026-05-30",
    nextContact: "2026-06-10",
    updatedAt: "1sem",
    createdAt: "2026-05-22T00:00:00.000Z",
  },
];

export const MOCK_DEALS: Deal[] = [
  {
    id: "deal-001",
    name: "Super 99 — Snacks Verano 2026",
    country: "Panamá",
    category: "Snacks",
    fase: "Propuesta enviada",
    estadoKpi: "En proceso",
    contactPerson: "Roberto Gálvez",
    buyerPerson: "Ana Morales (Category Manager)",
    email: "r.galvez@super99.com.pa",
    email1: "compras@super99.com.pa",
    vendor: "Jenni Benarroch",
    lastContact: "2026-06-07",
    nextAction: "2026-06-14",
    targetMonth: "Julio 2026",
    targetValue: "12,000",
    lastNotes: "Enviada propuesta exhibidor isla verano. Esperando aprobación de compras.",
    updatedAt: "2d",
  },
  {
    id: "deal-002",
    name: "Distribuidora Rojas — Confitería Q3",
    country: "Costa Rica",
    category: "Confitería",
    fase: "Negociación",
    estadoKpi: "Avanzado",
    contactPerson: "Luis Rojas",
    buyerPerson: "Luis Rojas (Dueño)",
    email: "luis@rojashijos.cr",
    email1: "",
    vendor: "Carlos Méndez",
    lastContact: "2026-06-08",
    nextAction: "2026-06-11",
    targetMonth: "Junio 2026",
    targetValue: "8,500",
    lastNotes: "Acordaron precio. Falta confirmación de volumen mínimo.",
    updatedAt: "ayer",
  },
  {
    id: "deal-003",
    name: "Massy Stores — Bebidas Temporada",
    country: "Trinidad",
    category: "Bebidas",
    fase: "Primer contacto",
    estadoKpi: "Nuevo",
    contactPerson: "Diane Alexander",
    buyerPerson: "",
    email: "d.alexander@massy.tt",
    email1: "",
    vendor: "María López",
    lastContact: "2026-06-09",
    nextAction: "2026-06-16",
    targetMonth: "Agosto 2026",
    targetValue: "15,000",
    lastNotes: "Primer contacto exitoso. Muy interesados en línea de bebidas.",
    updatedAt: "hoy",
  },
  {
    id: "deal-004",
    name: "Maxibodega — Limpieza Hogar",
    country: "El Salvador",
    category: "Limpieza del Hogar",
    fase: "Propuesta enviada",
    estadoKpi: "En proceso",
    contactPerson: "Carmen Villalta",
    buyerPerson: "Jorge Rivas (Jefe Compras)",
    email: "c.villalta@maxibodega.sv",
    email1: "jrivas@maxibodega.sv",
    vendor: "Jenni Benarroch",
    lastContact: "2026-06-06",
    nextAction: "2026-06-13",
    targetMonth: "Julio 2026",
    targetValue: "9,200",
    lastNotes: "Propuesta de exhibidor presentada. Reunión agendada para el jueves.",
    updatedAt: "3d",
  },
  {
    id: "deal-005",
    name: "Super BM — Campaña Snacks",
    country: "Guatemala",
    category: "Snacks",
    fase: "Seguimiento",
    estadoKpi: "En proceso",
    contactPerson: "Pedro Castillo",
    buyerPerson: "Sofía Ramírez (Category Manager)",
    email: "p.castillo@superbm.gt",
    email1: "sramirez@superbm.gt",
    vendor: "María López",
    lastContact: "2026-06-09",
    nextAction: "2026-06-17",
    targetMonth: "Julio 2026",
    targetValue: "11,000",
    lastNotes: "Contacto efectivo hoy. Enviando propuesta esta semana.",
    updatedAt: "hoy",
  },
  {
    id: "deal-006",
    name: "PriceSmart CR — Confitería Navidad",
    country: "Costa Rica",
    category: "Confitería",
    fase: "Primer contacto",
    estadoKpi: "Nuevo",
    contactPerson: "Mariela Soto",
    buyerPerson: "",
    email: "m.soto@pricesmart.com",
    email1: "",
    vendor: "Jenni Benarroch",
    lastContact: "2026-06-02",
    nextAction: "2026-06-10",
    targetMonth: "Noviembre 2026",
    targetValue: "25,000",
    lastNotes: "Interesados en temporada navideña. Piden catálogo completo.",
    updatedAt: "1sem",
  },
  {
    id: "deal-007",
    name: "Automercado — Cuidado Personal",
    country: "Costa Rica",
    category: "Cuidado Personal",
    fase: "Cierre",
    estadoKpi: "Avanzado",
    contactPerson: "Ricardo Ureña",
    buyerPerson: "Ricardo Ureña (Compras)",
    email: "r.urena@automercado.cr",
    email1: "",
    vendor: "Carlos Méndez",
    lastContact: "2026-06-07",
    nextAction: "2026-06-12",
    targetMonth: "Junio 2026",
    targetValue: "18,000",
    lastNotes: "Orden de compra en proceso de aprobación interna.",
    updatedAt: "2d",
  },
  {
    id: "deal-008",
    name: "Hi-Lo Jamaica — Bebidas Verano",
    country: "Jamaica",
    category: "Bebidas",
    fase: "Propuesta enviada",
    estadoKpi: "En proceso",
    contactPerson: "Michael Brown",
    buyerPerson: "Sandra Clarke (Purchasing Manager)",
    email: "m.brown@hilo.com.jm",
    email1: "s.clarke@hilo.com.jm",
    vendor: "María López",
    lastContact: "2026-06-04",
    nextAction: "2026-06-12",
    targetMonth: "Julio 2026",
    targetValue: "14,000",
    lastNotes: "Proposal sent for summer activation. Awaiting board approval.",
    updatedAt: "5d",
  },
  {
    id: "deal-009",
    name: "Walmart Guatemala — Snacks Q3",
    country: "Guatemala",
    category: "Snacks",
    fase: "Seguimiento",
    estadoKpi: "En riesgo",
    contactPerson: "Andrea Fuentes",
    buyerPerson: "Marco Herrera (Buyer)",
    email: "afuentes@walmart.com.gt",
    email1: "mherrera@walmart.com.gt",
    vendor: "Carlos Méndez",
    lastContact: "2026-05-20",
    nextAction: "2026-06-09",
    targetMonth: "Agosto 2026",
    targetValue: "22,000",
    lastNotes: "Sin respuesta desde hace 3 semanas. Requiere seguimiento urgente.",
    updatedAt: "3sem",
  },
  {
    id: "deal-010",
    name: "Do it Center Jamaica — Confitería",
    country: "Jamaica",
    category: "Confitería",
    fase: "Primer contacto",
    estadoKpi: "Nuevo",
    contactPerson: "Kevin Thompson",
    buyerPerson: "",
    email: "k.thompson@doitcenter.jm",
    email1: "",
    vendor: "Jenni Benarroch",
    lastContact: "2026-05-15",
    nextAction: "2026-06-10",
    targetMonth: "Septiembre 2026",
    targetValue: "7,500",
    lastNotes: "Initial contact made. Interest in confectionery display stand.",
    updatedAt: "3sem",
  },
];
