import type { Prospect, Deal } from "@/lib/types";

// ── Datos ficticios para desarrollo local ─────────────────────────────────────
// Actívados con NEXT_PUBLIC_USE_MOCK=true en .env.local
// NUNCA se usan en producción (la variable no existe en Vercel)

export type SuggestedProspect = {
  id: string;
  name: string;
  country: string;
  category: string;
  razon: string;         // por qué la IA los sugiere
  contactoCargo: string; // cargo estimado del comprador de categoría
  canal: "WhatsApp" | "Email";
  semana: string;        // "2026-W24"
  idioma: "es" | "en";
};

// Semana 9–15 junio 2026 (W24)
export const MOCK_SUGGESTED_PROSPECTS: SuggestedProspect[] = [
  {
    id: "sug-001",
    name: "Hipermás El Salvador",
    country: "El Salvador",
    category: "Snacks & Confitería",
    razon: "Cadena de 18 hipermercados. Sin distribuidor activo en categoría Snacks según perfil LinkedIn de su equipo de compras.",
    contactoCargo: "Jefe de Compras",
    canal: "WhatsApp",
    semana: "2026-W24",
    idioma: "es",
  },
  {
    id: "sug-002",
    name: "Distribuidora Castillo & Asociados",
    country: "Honduras",
    category: "Bebidas & Snacks",
    razon: "Distribuidora regional con cobertura en 6 departamentos. Busca ampliar portafolio de snacks para el canal tradicional.",
    contactoCargo: "Gerente Comercial",
    canal: "WhatsApp",
    semana: "2026-W24",
    idioma: "es",
  },
  {
    id: "sug-003",
    name: "Selectos Supermercados",
    country: "El Salvador",
    category: "Confitería",
    razon: "Cadena nacional con 25 puntos de venta. Su exhibidor de confitería lleva más de 6 meses sin renovar proveedor.",
    contactoCargo: "Category Manager",
    canal: "Email",
    semana: "2026-W24",
    idioma: "es",
  },
  {
    id: "sug-004",
    name: "Super Selectos Nicaragua",
    country: "Nicaragua",
    category: "Limpieza del Hogar",
    razon: "Segunda cadena de supermercados del país. Perfil de compras activo en LinkedIn con búsquedas recientes de proveedores de limpieza.",
    contactoCargo: "Jefe de Compras",
    canal: "WhatsApp",
    semana: "2026-W24",
    idioma: "es",
  },
  {
    id: "sug-005",
    name: "IGA Supermarkets Jamaica",
    country: "Jamaica",
    category: "Bebidas & Confitería",
    razon: "Franquicia IGA con 9 tiendas en Kingston y Montego Bay. Compradores activos en ferias regionales del Caribe.",
    contactoCargo: "Purchasing Manager",
    canal: "Email",
    semana: "2026-W24",
    idioma: "en",
  },
  {
    id: "sug-006",
    name: "Mega Depot Trinidad",
    country: "Trinidad",
    category: "Snacks & Limpieza del Hogar",
    razon: "Cash & Carry mayorista con 3 sucursales. Importa directamente de Panamá y Colombia. Contacto identificado en directorio TTMA.",
    contactoCargo: "Procurement Manager",
    canal: "Email",
    semana: "2026-W24",
    idioma: "en",
  },
  {
    id: "sug-007",
    name: "La Torre Guatemala",
    country: "Guatemala",
    category: "Cuidado Personal",
    razon: "Cadena de tiendas de descuento con presencia en 12 ciudades. Alta rotación en categoría cuidado personal según reporte sectorial.",
    contactoCargo: "Gerente de Compras",
    canal: "WhatsApp",
    semana: "2026-W24",
    idioma: "es",
  },
  {
    id: "sug-008",
    name: "Courts Barbados",
    country: "Barbados",
    category: "Confitería & Snacks",
    razon: "Retail establecido en Bridgetown con sección de alimentos en expansión. Busca proveedores latinoamericanos según su newsletter comercial.",
    contactoCargo: "Buying Manager",
    canal: "Email",
    semana: "2026-W24",
    idioma: "en",
  },
  {
    id: "sug-009",
    name: "Corporación Multi Inversiones CR",
    country: "Costa Rica",
    category: "Snacks & Bebidas",
    razon: "Grupo empresarial con cadena Pollo Campero y puntos retail. Licitación abierta para snacks en canales de conveniencia.",
    contactoCargo: "Category Manager",
    canal: "WhatsApp",
    semana: "2026-W24",
    idioma: "es",
  },
  {
    id: "sug-010",
    name: "United Grocers Barbados",
    country: "Barbados",
    category: "Bebidas & Limpieza del Hogar",
    razon: "Mayorista caribeño con red de 40 clientes minoristas en Barbados y Santa Lucía. Asistente a feria CHTA 2026.",
    contactoCargo: "Sales & Purchasing Director",
    canal: "Email",
    semana: "2026-W24",
    idioma: "en",
  },
];

export const MOCK_PROSPECTS: Prospect[] = [
  // ── Antigua y Barbuda ──────────────────────────────────────────────────────
  { id: "mock-001", name: "Caribbean School Supplies Ltd",    country: "Antigua y Barbuda",         status: "contacto efectivo",seller: "Daniel",       vendorIds: [], category: "Papelería & Útiles",        lastContact: "2026-06-09", nextContact: "2026-06-16", updatedAt: "hoy",  createdAt: "2026-06-09T00:00:00Z", contactPerson: "Marcus Joseph" },
  { id: "mock-002", name: "Fun Zone Toys Antigua",            country: "Antigua y Barbuda",         status: "sin acción",       seller: "Daniel",       vendorIds: [], category: "Juguetería & Entretenimiento",lastContact: "2026-05-28", nextContact: "2026-06-14", updatedAt: "1sem", createdAt: "2026-04-15T00:00:00Z", contactPerson: "Diane Williams" },
  // ── Argentina ──────────────────────────────────────────────────────────────
  { id: "mock-003", name: "DISMEX Argentina Papelería",       country: "Argentina",                 status: "contacto efectivo",seller: "Orlando",      vendorIds: [], category: "Papelería & Útiles",        lastContact: "2026-06-10", nextContact: "2026-06-17", updatedAt: "hoy",  createdAt: "2026-06-10T00:00:00Z", contactPerson: "Valentina Russo" },
  { id: "mock-004", name: "Almacén El Gaucho SA",             country: "Argentina",                 status: "sin acción",       seller: "Orlando",      vendorIds: [], category: "Almacén General",            lastContact: "2026-05-28", nextContact: "2026-06-14", updatedAt: "1sem", createdAt: "2026-05-05T00:00:00Z", contactPerson: "Diego Fernández" },
  // ── Aruba ──────────────────────────────────────────────────────────────────
  { id: "mock-005", name: "ABC Bookstore Aruba",              country: "Aruba",                     status: "negociación",      seller: "Daniel",       vendorIds: [], category: "Librería & Editorial",       lastContact: "2026-06-07", nextContact: "2026-06-14", updatedAt: "2d",   createdAt: "2026-04-20T00:00:00Z", contactPerson: "Sandra Ling" },
  { id: "mock-006", name: "Island Home Center Aruba",         country: "Aruba",                     status: "sin acción",       seller: "Daniel",       vendorIds: [], category: "Hogar & Decoración",         lastContact: "2026-05-15", nextContact: "2026-06-10", updatedAt: "3sem", createdAt: "2026-05-08T00:00:00Z", contactPerson: "Peter Kong" },
  // ── Bahamas ────────────────────────────────────────────────────────────────
  { id: "mock-007", name: "Nassau Office Supplies Ltd",       country: "Bahamas",                   status: "propuesta enviada",seller: "Daniel",       vendorIds: [], category: "Papelería & Útiles",        lastContact: "2026-06-09", nextContact: "2026-06-16", updatedAt: "hoy",  createdAt: "2026-06-09T00:00:00Z", contactPerson: "Trevor Rolle" },
  { id: "mock-008", name: "Bahamas Toy World",                country: "Bahamas",                   status: "contacto efectivo",seller: "Daniel",       vendorIds: [], category: "Juguetería & Entretenimiento",lastContact: "2026-06-04", nextContact: "2026-06-15", updatedAt: "5d",   createdAt: "2026-05-20T00:00:00Z", contactPerson: "Angela Solomon" },
  // ── Barbados ───────────────────────────────────────────────────────────────
  { id: "mock-009", name: "Barbados Book Depot",              country: "Barbados",                  status: "sin acción",       seller: "Daniel",       vendorIds: [], category: "Librería & Editorial",       lastContact: "2026-05-28", nextContact: "2026-06-11", updatedAt: "1sem", createdAt: "2026-05-18T00:00:00Z", contactPerson: "David Clarke" },
  { id: "mock-010", name: "Island Pharmacy Barbados",         country: "Barbados",                  status: "propuesta enviada",seller: "Daniel",       vendorIds: [], category: "Farmacia & Salud",           lastContact: "2026-06-04", nextContact: "2026-06-16", updatedAt: "5d",   createdAt: "2026-04-25T00:00:00Z", contactPerson: "Natalie Gill" },
  // ── Belize ─────────────────────────────────────────────────────────────────
  { id: "mock-011", name: "Belize City Stationery Ltd",       country: "Belize",                    status: "sin acción",       seller: "Daniel",       vendorIds: [], category: "Papelería & Útiles",        lastContact: "2026-06-02", nextContact: "2026-06-12", updatedAt: "1sem", createdAt: "2026-05-22T00:00:00Z", contactPerson: "Linda Trapp" },
  { id: "mock-012", name: "Brodies Superstore Belize",        country: "Belize",                    status: "contacto efectivo",seller: "Daniel",       vendorIds: [], category: "Supermercado",               lastContact: "2026-06-08", nextContact: "2026-06-15", updatedAt: "ayer", createdAt: "2026-05-01T00:00:00Z", contactPerson: "Carlos Mira" },
  // ── Bolivia ────────────────────────────────────────────────────────────────
  { id: "mock-013", name: "Librería Los Andes Bolivia",       country: "Bolivia",                   status: "propuesta enviada",seller: "John",         vendorIds: [], category: "Librería & Editorial",       lastContact: "2026-06-10", nextContact: "2026-06-17", updatedAt: "hoy",  createdAt: "2026-06-10T00:00:00Z", contactPerson: "Paola Vargas" },
  { id: "mock-014", name: "Farmacia Bolivia SA",              country: "Bolivia",                   status: "sin acción",       seller: "John",         vendorIds: [], category: "Farmacia & Salud",           lastContact: "2026-05-20", nextContact: "2026-06-13", updatedAt: "3sem", createdAt: "2026-05-14T00:00:00Z", contactPerson: "Jorge Morales" },
  // ── Chile ──────────────────────────────────────────────────────────────────
  { id: "mock-015", name: "Dist. Útiles Escolares Chile",     country: "Chile",                     status: "contacto efectivo",seller: "Joaquin",      vendorIds: [], category: "Papelería & Útiles",        lastContact: "2026-06-11", nextContact: "2026-06-18", updatedAt: "hoy",  createdAt: "2026-06-11T00:00:00Z", contactPerson: "Isidora Pizarro" },
  { id: "mock-016", name: "Juguetería El Niño Feliz Chile",   country: "Chile",                     status: "sin acción",       seller: "Joaquin",      vendorIds: [], category: "Juguetería & Entretenimiento",lastContact: "2026-06-01", nextContact: "2026-06-15", updatedAt: "1sem", createdAt: "2026-05-05T00:00:00Z", contactPerson: "Rodrigo Soto" },
  // ── Colombia ───────────────────────────────────────────────────────────────
  { id: "mock-017", name: "Dist. Panamericana Colombia",      country: "Colombia",                  status: "contacto efectivo",seller: "John",         vendorIds: [], category: "Papelería & Útiles",        lastContact: "2026-06-09", nextContact: "2026-06-16", updatedAt: "hoy",  createdAt: "2026-06-09T00:00:00Z", contactPerson: "Catalina Gómez" },
  { id: "mock-018", name: "Almacén Hogar Colombia",           country: "Colombia",                  status: "sin acción",       seller: "John",         vendorIds: [], category: "Hogar & Decoración",         lastContact: "2026-05-25", nextContact: "2026-06-12", updatedAt: "2sem", createdAt: "2026-04-28T00:00:00Z", contactPerson: "Andrés Peñaloza" },
  // ── Costa Rica ─────────────────────────────────────────────────────────────
  { id: "mock-019", name: "Librería Universal CR",            country: "Costa Rica",                status: "negociación",      seller: "John",         vendorIds: [], category: "Librería & Editorial",       lastContact: "2026-06-12", nextContact: "2026-06-19", updatedAt: "hoy",  createdAt: "2026-06-12T00:00:00Z", contactPerson: "Ricardo Ureña" },
  { id: "mock-020", name: "Farmacia La Botica CR",            country: "Costa Rica",                status: "propuesta enviada",seller: "John",         vendorIds: [], category: "Farmacia & Salud",           lastContact: "2026-06-02", nextContact: "2026-06-16", updatedAt: "1sem", createdAt: "2026-05-22T00:00:00Z", contactPerson: "Laura Chinchilla" },
  // ── Cuba ───────────────────────────────────────────────────────────────────
  { id: "mock-021", name: "Almacén El Capitolio Cuba",        country: "Cuba",                      status: "sin acción",       seller: "Daniel",       vendorIds: [], category: "Almacén General",            lastContact: "2026-05-10", nextContact: "2026-06-10", updatedAt: "1mes", createdAt: "2026-04-05T00:00:00Z", contactPerson: "Yolanda Pérez" },
  { id: "mock-022", name: "Librería Cervantes Cuba",          country: "Cuba",                      status: "contacto efectivo",seller: "Daniel",       vendorIds: [], category: "Librería & Editorial",       lastContact: "2026-06-07", nextContact: "2026-06-15", updatedAt: "2d",   createdAt: "2026-04-20T00:00:00Z", contactPerson: "Ramón Suárez" },
  // ── Curaçao ────────────────────────────────────────────────────────────────
  { id: "mock-023", name: "Boekhandel El Mundo Curaçao",      country: "Curaçao",                   status: "sin acción",       seller: "Daniel",       vendorIds: [], category: "Librería & Editorial",       lastContact: "2026-05-20", nextContact: "2026-06-12", updatedAt: "3sem", createdAt: "2026-05-15T00:00:00Z", contactPerson: "Rosalina Martina" },
  { id: "mock-024", name: "Island Toys Curaçao",              country: "Curaçao",                   status: "propuesta enviada",seller: "Daniel",       vendorIds: [], category: "Juguetería & Entretenimiento",lastContact: "2026-06-05", nextContact: "2026-06-14", updatedAt: "4d",   createdAt: "2026-04-30T00:00:00Z", contactPerson: "Michel van den Berg" },
  // ── Dominica ───────────────────────────────────────────────────────────────
  { id: "mock-025", name: "Dominica Office Supplies",         country: "Dominica",                  status: "sin acción",       seller: "Daniel",       vendorIds: [], category: "Papelería & Útiles",        lastContact: "2026-05-22", nextContact: "2026-06-11", updatedAt: "2sem", createdAt: "2026-05-02T00:00:00Z", contactPerson: "Paula Astaphan" },
  { id: "mock-026", name: "Nature Isle Pharmacy Dominica",    country: "Dominica",                  status: "propuesta enviada",seller: "Daniel",       vendorIds: [], category: "Farmacia & Salud",           lastContact: "2026-06-04", nextContact: "2026-06-15", updatedAt: "5d",   createdAt: "2026-04-22T00:00:00Z", contactPerson: "Charles Whitchurch" },
  // ── Ecuador ────────────────────────────────────────────────────────────────
  { id: "mock-027", name: "Dist. El Maestro Ecuador",         country: "Ecuador",                   status: "contacto efectivo",seller: "Omar",         vendorIds: [], category: "Papelería & Útiles",        lastContact: "2026-06-10", nextContact: "2026-06-17", updatedAt: "hoy",  createdAt: "2026-06-10T00:00:00Z", contactPerson: "Sofía Andrade" },
  { id: "mock-028", name: "Farmacia Medicity Ecuador",        country: "Ecuador",                   status: "sin acción",       seller: "Omar",         vendorIds: [], category: "Farmacia & Salud",           lastContact: "2026-05-29", nextContact: "2026-06-13", updatedAt: "1sem", createdAt: "2026-05-10T00:00:00Z", contactPerson: "Luis Espinoza" },
  // ── El Salvador ────────────────────────────────────────────────────────────
  { id: "mock-029", name: "Almacén El Mercado SV",            country: "El Salvador",               status: "propuesta enviada",seller: "Omar",         vendorIds: [], category: "Almacén General",            lastContact: "2026-06-11", nextContact: "2026-06-18", updatedAt: "hoy",  createdAt: "2026-06-11T00:00:00Z", contactPerson: "Héctor Guzmán" },
  { id: "mock-030", name: "Librería Don Bosco ES",            country: "El Salvador",               status: "sin acción",       seller: "Omar",         vendorIds: [], category: "Librería & Editorial",       lastContact: "2026-06-02", nextContact: "2026-06-14", updatedAt: "1sem", createdAt: "2026-05-15T00:00:00Z", contactPerson: "Carmen Villalta" },
  // ── Guatemala ──────────────────────────────────────────────────────────────
  { id: "mock-031", name: "Dist. Guatemalteca de Papelería",  country: "Guatemala",                 status: "contacto efectivo",seller: "Omar",         vendorIds: [], category: "Papelería & Útiles",        lastContact: "2026-06-09", nextContact: "2026-06-16", updatedAt: "hoy",  createdAt: "2026-06-09T00:00:00Z", contactPerson: "Andrea Fuentes" },
  { id: "mock-032", name: "Juguetería La Ilusión GT",         country: "Guatemala",                 status: "sin acción",       seller: "Omar",         vendorIds: [], category: "Juguetería & Entretenimiento",lastContact: "2026-06-04", nextContact: "2026-06-13", updatedAt: "5d",   createdAt: "2026-05-28T00:00:00Z", contactPerson: "Fernando Castillo" },
  // ── Guyana ─────────────────────────────────────────────────────────────────
  { id: "mock-033", name: "Giftland Superstore Guyana",       country: "Guyana",                    status: "propuesta enviada",seller: "Omar",         vendorIds: [], category: "Almacén General",            lastContact: "2026-06-03", nextContact: "2026-06-14", updatedAt: "6d",   createdAt: "2026-05-10T00:00:00Z", contactPerson: "Ramona Singh" },
  { id: "mock-034", name: "Austin's Book Services GY",        country: "Guyana",                    status: "sin acción",       seller: "Omar",         vendorIds: [], category: "Librería & Editorial",       lastContact: "2026-05-19", nextContact: "2026-06-12", updatedAt: "3sem", createdAt: "2026-04-28T00:00:00Z", contactPerson: "Patrick Fernandes" },
  // ── Haití ──────────────────────────────────────────────────────────────────
  { id: "mock-035", name: "Librairie La Pléiade Haïti",       country: "Haití",                     status: "sin acción",       seller: "Daniel",       vendorIds: [], category: "Librería & Editorial",       lastContact: "2026-05-12", nextContact: "2026-06-10", updatedAt: "1mes", createdAt: "2026-04-10T00:00:00Z", contactPerson: "Jean-Paul Moise" },
  { id: "mock-036", name: "Pharmed Distribution Haïti",       country: "Haití",                     status: "propuesta enviada",seller: "Daniel",       vendorIds: [], category: "Farmacia & Salud",           lastContact: "2026-06-01", nextContact: "2026-06-15", updatedAt: "1sem", createdAt: "2026-05-05T00:00:00Z", contactPerson: "Marie Flore Joseph" },
  // ── Honduras ───────────────────────────────────────────────────────────────
  { id: "mock-037", name: "Librería El Hogar Hondureño",      country: "Honduras",                  status: "propuesta enviada",seller: "John",         vendorIds: [], category: "Librería & Editorial",       lastContact: "2026-06-12", nextContact: "2026-06-19", updatedAt: "hoy",  createdAt: "2026-06-12T00:00:00Z", contactPerson: "Claudia Reyes" },
  { id: "mock-038", name: "Supermercado La Colonia HN",       country: "Honduras",                  status: "contacto efectivo",seller: "John",         vendorIds: [], category: "Supermercado",               lastContact: "2026-06-09", nextContact: "2026-06-17", updatedAt: "hoy",  createdAt: "2026-05-18T00:00:00Z", contactPerson: "David Molina" },
  // ── Islas Caimán ───────────────────────────────────────────────────────────
  { id: "mock-039", name: "Cayman Book Nook Ltd",             country: "Islas Caimán",              status: "contacto efectivo",seller: "Daniel",       vendorIds: [], category: "Librería & Editorial",       lastContact: "2026-06-08", nextContact: "2026-06-15", updatedAt: "ayer", createdAt: "2026-05-08T00:00:00Z", contactPerson: "Amanda Foster" },
  { id: "mock-040", name: "Island Pharmacy Cayman",           country: "Islas Caimán",              status: "sin acción",       seller: "Daniel",       vendorIds: [], category: "Farmacia & Salud",           lastContact: "2026-05-20", nextContact: "2026-06-11", updatedAt: "3sem", createdAt: "2026-04-28T00:00:00Z", contactPerson: "Brian Hurley" },
  // ── Islas Turcos y Caicos ──────────────────────────────────────────────────
  { id: "mock-041", name: "TCI School Supplies",              country: "Islas Turcos y Caicos",     status: "propuesta enviada",seller: "Daniel",       vendorIds: [], category: "Papelería & Útiles",        lastContact: "2026-06-08", nextContact: "2026-06-16", updatedAt: "ayer", createdAt: "2026-05-14T00:00:00Z", contactPerson: "James Graceway" },
  { id: "mock-042", name: "Grand Turk Pharmacy",              country: "Islas Turcos y Caicos",     status: "sin acción",       seller: "Daniel",       vendorIds: [], category: "Farmacia & Salud",           lastContact: "2026-05-25", nextContact: "2026-06-12", updatedAt: "2sem", createdAt: "2026-05-01T00:00:00Z", contactPerson: "Tamara Williams" },
  // ── Islas Vírgenes Americanas ──────────────────────────────────────────────
  { id: "mock-043", name: "VI Stationery & Office Supply",    country: "Islas Vírgenes Americanas", status: "sin acción",       seller: "Daniel",       vendorIds: [], category: "Papelería & Útiles",        lastContact: "2026-06-03", nextContact: "2026-06-14", updatedAt: "6d",   createdAt: "2026-05-12T00:00:00Z", contactPerson: "Patricia Moore" },
  { id: "mock-044", name: "Crown Bay Pharmacy USVI",          country: "Islas Vírgenes Americanas", status: "contacto efectivo",seller: "Daniel",       vendorIds: [], category: "Farmacia & Salud",           lastContact: "2026-06-08", nextContact: "2026-06-16", updatedAt: "ayer", createdAt: "2026-04-30T00:00:00Z", contactPerson: "Robert Sprauve" },
  // ── Islas Vírgenes Británicas ──────────────────────────────────────────────
  { id: "mock-045", name: "BVI Bookstore Ltd",                country: "Islas Vírgenes Británicas", status: "propuesta enviada",seller: "Daniel",       vendorIds: [], category: "Librería & Editorial",       lastContact: "2026-06-07", nextContact: "2026-06-15", updatedAt: "2d",   createdAt: "2026-05-20T00:00:00Z", contactPerson: "Lisa Penn" },
  { id: "mock-046", name: "Road Town Pharmacy BVI",           country: "Islas Vírgenes Británicas", status: "sin acción",       seller: "Daniel",       vendorIds: [], category: "Farmacia & Salud",           lastContact: "2026-05-22", nextContact: "2026-06-12", updatedAt: "2sem", createdAt: "2026-05-05T00:00:00Z", contactPerson: "Dennis Cary" },
  // ── Jamaica ────────────────────────────────────────────────────────────────
  { id: "mock-047", name: "Kingston Bookshop Jamaica",        country: "Jamaica",                   status: "contacto efectivo",seller: "Daniel",       vendorIds: [], category: "Librería & Editorial",       lastContact: "2026-06-10", nextContact: "2026-06-17", updatedAt: "hoy",  createdAt: "2026-06-10T00:00:00Z", contactPerson: "Sandra Clarke" },
  { id: "mock-048", name: "Caribbean Toy Distributors JM",    country: "Jamaica",                   status: "sin acción",       seller: "Daniel",       vendorIds: [], category: "Juguetería & Entretenimiento",lastContact: "2026-05-22", nextContact: "2026-06-12", updatedAt: "2sem", createdAt: "2026-05-05T00:00:00Z", contactPerson: "Wayne Thompson" },
  // ── Martinica ──────────────────────────────────────────────────────────────
  { id: "mock-049", name: "Librairie Antillaise Martinique",  country: "Martinica",                 status: "sin acción",       seller: "Daniel",       vendorIds: [], category: "Librería & Editorial",       lastContact: "2026-05-15", nextContact: "2026-06-11", updatedAt: "3sem", createdAt: "2026-05-10T00:00:00Z", contactPerson: "Sophie Beaumont" },
  { id: "mock-050", name: "Jouets Tropicaux Martinique",      country: "Martinica",                 status: "propuesta enviada",seller: "Daniel",       vendorIds: [], category: "Juguetería & Entretenimiento",lastContact: "2026-06-05", nextContact: "2026-06-14", updatedAt: "4d",   createdAt: "2026-04-25T00:00:00Z", contactPerson: "François Lemaire" },
  // ── México ─────────────────────────────────────────────────────────────────
  { id: "mock-051", name: "DISMEX Distribuidora Papelería MX",country: "México",                    status: "contacto efectivo",seller: "Joaquin",      vendorIds: [], category: "Papelería & Útiles",        lastContact: "2026-06-11", nextContact: "2026-06-18", updatedAt: "hoy",  createdAt: "2026-06-11T00:00:00Z", contactPerson: "Alejandra Torres" },
  { id: "mock-052", name: "Juguetería El Palacio del Niño MX",country: "México",                    status: "sin acción",       seller: "Joaquin",      vendorIds: [], category: "Juguetería & Entretenimiento",lastContact: "2026-06-04", nextContact: "2026-06-13", updatedAt: "5d",   createdAt: "2026-05-08T00:00:00Z", contactPerson: "Roberto Chedraui" },
  // ── Nicaragua ──────────────────────────────────────────────────────────────
  { id: "mock-053", name: "Almacén El Éxito Nicaragua",       country: "Nicaragua",                 status: "propuesta enviada",seller: "John",         vendorIds: [], category: "Almacén General",            lastContact: "2026-06-09", nextContact: "2026-06-16", updatedAt: "hoy",  createdAt: "2026-06-09T00:00:00Z", contactPerson: "Martha Espinoza" },
  { id: "mock-054", name: "Farmacia Vida Nicaragua",          country: "Nicaragua",                 status: "sin acción",       seller: "John",         vendorIds: [], category: "Farmacia & Salud",           lastContact: "2026-05-25", nextContact: "2026-06-12", updatedAt: "2sem", createdAt: "2026-05-05T00:00:00Z", contactPerson: "Carlos Gutiérrez" },
  // ── Panamá ─────────────────────────────────────────────────────────────────
  { id: "mock-055", name: "Dist. Istmeña de Papelería PA",    country: "Panamá",                    status: "contacto efectivo",seller: "John",         vendorIds: [], category: "Papelería & Útiles",        lastContact: "2026-06-12", nextContact: "2026-06-19", updatedAt: "hoy",  createdAt: "2026-06-12T00:00:00Z", contactPerson: "Roberto Díaz" },
  { id: "mock-056", name: "Juguetería Fantasía Panamá",       country: "Panamá",                    status: "propuesta enviada",seller: "John",         vendorIds: [], category: "Juguetería & Entretenimiento",lastContact: "2026-06-05", nextContact: "2026-06-15", updatedAt: "4d",   createdAt: "2026-05-10T00:00:00Z", contactPerson: "Mireya Castillo" },
  // ── Paraguay ───────────────────────────────────────────────────────────────
  { id: "mock-057", name: "Librería El Libro Paraguayo",      country: "Paraguay",                  status: "sin acción",       seller: "Joaquin",      vendorIds: [], category: "Librería & Editorial",       lastContact: "2026-05-28", nextContact: "2026-06-13", updatedAt: "1sem", createdAt: "2026-05-05T00:00:00Z", contactPerson: "Lorena Benítez" },
  { id: "mock-058", name: "Farmacia Catedral Paraguay",       country: "Paraguay",                  status: "contacto efectivo",seller: "Joaquin",      vendorIds: [], category: "Farmacia & Salud",           lastContact: "2026-06-07", nextContact: "2026-06-16", updatedAt: "2d",   createdAt: "2026-05-18T00:00:00Z", contactPerson: "Hugo Zacarías" },
  // ── Perú ───────────────────────────────────────────────────────────────────
  { id: "mock-059", name: "Dist. Peruana de Útiles Escolares",country: "Perú",                      status: "propuesta enviada",seller: "Omar",         vendorIds: [], category: "Papelería & Útiles",        lastContact: "2026-06-10", nextContact: "2026-06-17", updatedAt: "hoy",  createdAt: "2026-06-10T00:00:00Z", contactPerson: "Mónica Huamán" },
  { id: "mock-060", name: "Almacén El Sol Perú",              country: "Perú",                      status: "sin acción",       seller: "Omar",         vendorIds: [], category: "Almacén General",            lastContact: "2026-05-26", nextContact: "2026-06-12", updatedAt: "2sem", createdAt: "2026-05-08T00:00:00Z", contactPerson: "César Quispe" },
  // ── Puerto Rico ────────────────────────────────────────────────────────────
  { id: "mock-061", name: "Librería La Tertulia PR",          country: "Puerto Rico",               status: "sin acción",       seller: "Joaquin",      vendorIds: [], category: "Librería & Editorial",       lastContact: "2026-06-01", nextContact: "2026-06-13", updatedAt: "1sem", createdAt: "2026-04-15T00:00:00Z", contactPerson: "Carmen Colón" },
  { id: "mock-062", name: "Farmacia El Yunque PR",            country: "Puerto Rico",               status: "propuesta enviada",seller: "Joaquin",      vendorIds: [], category: "Farmacia & Salud",           lastContact: "2026-06-06", nextContact: "2026-06-14", updatedAt: "3d",   createdAt: "2026-05-12T00:00:00Z", contactPerson: "José Méndez" },
  // ── República Dominicana ───────────────────────────────────────────────────
  { id: "mock-063", name: "Dist. Caribeña de Papelería RD",   country: "República Dominicana",      status: "contacto efectivo",seller: "Orlando",      vendorIds: [], category: "Papelería & Útiles",        lastContact: "2026-06-11", nextContact: "2026-06-18", updatedAt: "hoy",  createdAt: "2026-06-11T00:00:00Z", contactPerson: "Ana Reyes" },
  { id: "mock-064", name: "Juguetería El Niño Dominicano",    country: "República Dominicana",      status: "sin acción",       seller: "Orlando",      vendorIds: [], category: "Juguetería & Entretenimiento",lastContact: "2026-05-24", nextContact: "2026-06-11", updatedAt: "2sem", createdAt: "2026-05-04T00:00:00Z", contactPerson: "Rafael Martínez" },
  // ── Sint Maarten ───────────────────────────────────────────────────────────
  { id: "mock-065", name: "Sint Maarten Bookshop SXM",        country: "Sint Maarten",              status: "sin acción",       seller: "Daniel",       vendorIds: [], category: "Librería & Editorial",       lastContact: "2026-05-20", nextContact: "2026-06-11", updatedAt: "3sem", createdAt: "2026-05-14T00:00:00Z", contactPerson: "Isabelle Gijsbertha" },
  { id: "mock-066", name: "Island Toy Store SXM",             country: "Sint Maarten",              status: "contacto efectivo",seller: "Daniel",       vendorIds: [], category: "Juguetería & Entretenimiento",lastContact: "2026-06-09", nextContact: "2026-06-17", updatedAt: "hoy",  createdAt: "2026-04-30T00:00:00Z", contactPerson: "Anthony Richardson" },
  // ── Trinidad y Tobago ──────────────────────────────────────────────────────
  { id: "mock-067", name: "T&T Stationery & Books",           country: "Trinidad y Tobago",         status: "contacto efectivo",seller: "Daniel",       vendorIds: [], category: "Papelería & Útiles",        lastContact: "2026-06-09", nextContact: "2026-06-16", updatedAt: "hoy",  createdAt: "2026-06-09T00:00:00Z", contactPerson: "Keisha Ramkissoon" },
  { id: "mock-068", name: "Drugs for Less Trinidad",          country: "Trinidad y Tobago",         status: "propuesta enviada",seller: "Daniel",       vendorIds: [], category: "Farmacia & Salud",           lastContact: "2026-06-05", nextContact: "2026-06-14", updatedAt: "4d",   createdAt: "2026-05-08T00:00:00Z", contactPerson: "Diane Alexander" },
  // ── Uruguay ────────────────────────────────────────────────────────────────
  { id: "mock-069", name: "Librería Puro Verso Uruguay",      country: "Uruguay",                   status: "propuesta enviada",seller: "Orlando",      vendorIds: [], category: "Librería & Editorial",       lastContact: "2026-06-12", nextContact: "2026-06-19", updatedAt: "hoy",  createdAt: "2026-06-12T00:00:00Z", contactPerson: "Gabriela Núñez" },
  { id: "mock-070", name: "Almacén El Mercado Uruguay",       country: "Uruguay",                   status: "sin acción",       seller: "Orlando",      vendorIds: [], category: "Almacén General",            lastContact: "2026-05-20", nextContact: "2026-06-13", updatedAt: "3sem", createdAt: "2026-04-22T00:00:00Z", contactPerson: "Marcelo Da Silva" },
  // ── Venezuela ──────────────────────────────────────────────────────────────
  { id: "mock-071", name: "Dist. Venezolana de Papelería",    country: "Venezuela",                 status: "contacto efectivo",seller: "Joaquin",      vendorIds: [], category: "Papelería & Útiles",        lastContact: "2026-06-10", nextContact: "2026-06-17", updatedAt: "hoy",  createdAt: "2026-06-10T00:00:00Z", contactPerson: "María Fernanda Blanco" },
  { id: "mock-072", name: "Farmacia Central Venezuela",       country: "Venezuela",                 status: "sin acción",       seller: "Joaquin",      vendorIds: [], category: "Farmacia & Salud",           lastContact: "2026-05-22", nextContact: "2026-06-12", updatedAt: "2sem", createdAt: "2026-05-05T00:00:00Z", contactPerson: "Carlos Rodríguez" },
];

export const MOCK_DEALS: Deal[] = [
  {
    id: "deal-001",
    name: "Super 99 — Snacks Verano 2026",
    country: "Panamá",
    category: "Snacks",
    fase: "Propuesta enviada",
    estadoKpi: "En proceso",
    contactPerson: "Roberto Gálvez",
    buyerPerson: "Ana Morales (Category Manager)",
    email: "r.galvez@super99.com.pa",
    email1: "compras@super99.com.pa",
    vendor: "Jenni Benarroch",
    lastContact: "2026-06-07",
    nextAction: "2026-06-14",
    targetMonth: "Julio 2026",
    targetValue: "12,000",
    lastNotes: "Enviada propuesta exhibidor isla verano. Esperando aprobación de compras.",
    updatedAt: "2d",
  },
  {
    id: "deal-002",
    name: "Distribuidora Rojas — Confitería Q3",
    country: "Costa Rica",
    category: "Confitería",
    fase: "Negociación",
    estadoKpi: "Avanzado",
    contactPerson: "Luis Rojas",
    buyerPerson: "Luis Rojas (Dueño)",
    email: "luis@rojashijos.cr",
    email1: "",
    vendor: "Carlos Méndez",
    lastContact: "2026-06-08",
    nextAction: "2026-06-11",
    targetMonth: "Junio 2026",
    targetValue: "8,500",
    lastNotes: "Acordaron precio. Falta confirmación de volumen mínimo.",
    updatedAt: "ayer",
  },
  {
    id: "deal-003",
    name: "Massy Stores — Bebidas Temporada",
    country: "Trinidad",
    category: "Bebidas",
    fase: "Primer contacto",
    estadoKpi: "Nuevo",
    contactPerson: "Diane Alexander",
    buyerPerson: "",
    email: "d.alexander@massy.tt",
    email1: "",
    vendor: "María López",
    lastContact: "2026-06-09",
    nextAction: "2026-06-16",
    targetMonth: "Agosto 2026",
    targetValue: "15,000",
    lastNotes: "Primer contacto exitoso. Muy interesados en línea de bebidas.",
    updatedAt: "hoy",
  },
  {
    id: "deal-004",
    name: "Maxibodega — Limpieza Hogar",
    country: "El Salvador",
    category: "Limpieza del Hogar",
    fase: "Propuesta enviada",
    estadoKpi: "En proceso",
    contactPerson: "Carmen Villalta",
    buyerPerson: "Jorge Rivas (Jefe Compras)",
    email: "c.villalta@maxibodega.sv",
    email1: "jrivas@maxibodega.sv",
    vendor: "Jenni Benarroch",
    lastContact: "2026-06-06",
    nextAction: "2026-06-13",
    targetMonth: "Julio 2026",
    targetValue: "9,200",
    lastNotes: "Propuesta de exhibidor presentada. Reunión agendada para el jueves.",
    updatedAt: "3d",
  },
  {
    id: "deal-005",
    name: "Super BM — Campaña Snacks",
    country: "Guatemala",
    category: "Snacks",
    fase: "Seguimiento",
    estadoKpi: "En proceso",
    contactPerson: "Pedro Castillo",
    buyerPerson: "Sofía Ramírez (Category Manager)",
    email: "p.castillo@superbm.gt",
    email1: "sramirez@superbm.gt",
    vendor: "María López",
    lastContact: "2026-06-09",
    nextAction: "2026-06-17",
    targetMonth: "Julio 2026",
    targetValue: "11,000",
    lastNotes: "Contacto efectivo hoy. Enviando propuesta esta semana.",
    updatedAt: "hoy",
  },
  {
    id: "deal-006",
    name: "PriceSmart CR — Confitería Navidad",
    country: "Costa Rica",
    category: "Confitería",
    fase: "Primer contacto",
    estadoKpi: "Nuevo",
    contactPerson: "Mariela Soto",
    buyerPerson: "",
    email: "m.soto@pricesmart.com",
    email1: "",
    vendor: "Jenni Benarroch",
    lastContact: "2026-06-02",
    nextAction: "2026-06-10",
    targetMonth: "Noviembre 2026",
    targetValue: "25,000",
    lastNotes: "Interesados en temporada navideña. Piden catálogo completo.",
    updatedAt: "1sem",
  },
  {
    id: "deal-007",
    name: "Automercado — Cuidado Personal",
    country: "Costa Rica",
    category: "Cuidado Personal",
    fase: "Cierre",
    estadoKpi: "Avanzado",
    contactPerson: "Ricardo Ureña",
    buyerPerson: "Ricardo Ureña (Compras)",
    email: "r.urena@automercado.cr",
    email1: "",
    vendor: "Carlos Méndez",
    lastContact: "2026-06-07",
    nextAction: "2026-06-12",
    targetMonth: "Junio 2026",
    targetValue: "18,000",
    lastNotes: "Orden de compra en proceso de aprobación interna.",
    updatedAt: "2d",
  },
  {
    id: "deal-008",
    name: "Hi-Lo Jamaica — Bebidas Verano",
    country: "Jamaica",
    category: "Bebidas",
    fase: "Propuesta enviada",
    estadoKpi: "En proceso",
    contactPerson: "Michael Brown",
    buyerPerson: "Sandra Clarke (Purchasing Manager)",
    email: "m.brown@hilo.com.jm",
    email1: "s.clarke@hilo.com.jm",
    vendor: "María López",
    lastContact: "2026-06-04",
    nextAction: "2026-06-12",
    targetMonth: "Julio 2026",
    targetValue: "14,000",
    lastNotes: "Proposal sent for summer activation. Awaiting board approval.",
    updatedAt: "5d",
  },
  {
    id: "deal-009",
    name: "Walmart Guatemala — Snacks Q3",
    country: "Guatemala",
    category: "Snacks",
    fase: "Seguimiento",
    estadoKpi: "En riesgo",
    contactPerson: "Andrea Fuentes",
    buyerPerson: "Marco Herrera (Buyer)",
    email: "afuentes@walmart.com.gt",
    email1: "mherrera@walmart.com.gt",
    vendor: "Carlos Méndez",
    lastContact: "2026-05-20",
    nextAction: "2026-06-09",
    targetMonth: "Agosto 2026",
    targetValue: "22,000",
    lastNotes: "Sin respuesta desde hace 3 semanas. Requiere seguimiento urgente.",
    updatedAt: "3sem",
  },
  {
    id: "deal-010",
    name: "Do it Center Jamaica — Confitería",
    country: "Jamaica",
    category: "Confitería",
    fase: "Primer contacto",
    estadoKpi: "Nuevo",
    contactPerson: "Kevin Thompson",
    buyerPerson: "",
    email: "k.thompson@doitcenter.jm",
    email1: "",
    vendor: "Jenni Benarroch",
    lastContact: "2026-05-15",
    nextAction: "2026-06-10",
    targetMonth: "Septiembre 2026",
    targetValue: "7,500",
    lastNotes: "Initial contact made. Interest in confectionery display stand.",
    updatedAt: "3sem",
  },
];
